runtime:
  container_commands:
  - apt-get update
  - apt-get install -y git
  python:
    version: '3.10'
    requirements:
    - pipeline-ai
    - torch
    - transformers
    - optimum
    - accelerate
    cuda_version: '11.4'
accelerators: ["l4"]
accelerator_memory: 10000
pipeline_graph: large-v2-detect-new:WhisperModel
pipeline_name: uriel/insane-whisper-v2
description: null
readme: null
extras: {}
